# Generated by Django 6.0.5 on 2026-06-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_alter_deal_associated_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealactivity',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='associated_lead',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
