# Generated by Django 6.0.5 on 2026-06-03 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_dealactivity_created_by_name_and_more'),
        ('leads', '0004_lead_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='associated_lead',
            field=models.ForeignKey(blank=True, db_column='associated_lead_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='leads.lead'),
        ),
    ]
